# Generated by Django 4.1.3 on 2022-11-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_chapter_options_studentcourseenrollment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '8. Chapters'},
        ),
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '10. Course Ratings'},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'verbose_name_plural': '9. Enrolled Courses'},
        ),
    ]
